name: Example workflow  
on:  
  workflow_dispatch:  
jobs:  
  example:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v2  
      - name: Run a one-line script  
        run: echo Hello, world!  
